#!/usr/bin/env python3
"""MORE's self-supervised collector: plain UCT generates its own training data.

This is MORE's System 2 phase. The paper is explicit that the data is free because the
search produces it: "we use the computed Q-values as ground-truth to train PPN. Note
that this computation data is free, since it is generated by the simulations performed
by MCTS." Their own run was 65,384 transitions from 243 training cases.

The search here is `mcts/`, not `mcts_network/`. It carries NO network:
`mcts_main.py:480` builds the root state without a push net, which is what lets MORE
bootstrap from nothing. `--prior uniform` gives us the same thing: `_make_planner`
returns a shell with `scorer=None`, so no checkpoint is loaded and no forward pass
happens. That independence is the point. MORE's arm shares the push primitives, the
simulator and the scenes with our work, and nothing else.

Deliberately mirrors aquaman_collect.py: the same episode derivation, the same env
setup, the same one-bad-scene-does-not-kill-a-shard policy, so the two corpora differ
by the search that produced them rather than by their plumbing.

Output, one JSONL line per episode:
  {xml, object_id, solved, sims, plan_len, budget,
   rows:   [{uid, depth, obj, edge, push_depth, label, num_visits, evidence}, ...]
   states: {uid: qpos}}

`label` is max(child.q) and `num_visits` is that child's visit count, which is what
lifelong_trainer weights its SmoothL1 by. `states` carries the simulator state each
row's push was taken from, so the 224x224 pictures render in a later pass instead of
inside the timed search.

  python more_collect.py --manifest M.txt --start 0 --end 100 --out shard.jsonl
"""
import argparse
import hashlib
import json
import os
import random
import sys
import time
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
SAGE = os.environ.get("SAGE_REPO", "")
for _p in (f"{REPO}/build_python", f"{REPO}/python", f"{REPO}/scripts", f"{REPO}/scripts/sandbox", SAGE):
    if _p and _p not in sys.path:
        sys.path.insert(0, _p)

from scorer_beam import make_env, read_manifest, FALLBACK_GOAL  # noqa: E402
from eval_bestfirst import _make_planner  # noqa: E402
from eval_m3 import sample_goal_points, goal_open_pts  # noqa: E402
from namo.core.xml_goal_parser import extract_goal_with_fallback  # noqa: E402
from namo.planners import get_region_snapshot  # noqa: E402
from namo.planners.opening.more_mcts import solve_scene_mcts  # noqa: E402

HMAX = 2
# MORE runs 300 MCTS iterations to collect (constants.py MCTS_ROLLOUTS comment,
# "300 for collection data") against 50 at deploy. Our budget is in simulator calls,
# not iterations, and one iteration costs an expansion plus a rollout, so this is a
# per-episode call cap in the same units the evaluation reports.
BUDGET = 600


def state_qpos(state):
    """Serialize a full-state object to a plain list, as aquaman_collect does."""
    for attr in ("qpos", "positions"):
        v = getattr(state, attr, None)
        if v is not None:
            return [float(x) for x in np.asarray(v).ravel()]
    raise TypeError(f"unknown state type {type(state)}: {dir(state)[:20]}")


def ep_hash(xml, obj):
    return int(hashlib.sha1(f"{xml}|{obj}".encode()).hexdigest()[:8], 16)


def derive_episodes(env):
    """(blocker_object, ...) for the robot->XML-goal 1-hop opening; [] if out of scope.

    Copied from aquaman_collect.derive_episodes so MORE trains on the same notion of an
    episode our own collector uses. A scene whose goal is more than one object away is
    out of scope here exactly as it is there.
    """
    snap = get_region_snapshot(env, goals_per_region=1, goal_radius=0.15, local_info_only=True,
                               seed=0, use_cpp_unified=True, use_xml_goal=True)
    robot = snap.get("robot_label")
    labels = set(snap["region_labels"].values()) if isinstance(snap["region_labels"], dict) else set()
    if not robot or robot in ("robot_goal", "goal"):
        return [], "robot_at_goal"
    if "goal" not in snap["adjacency"].get(robot, set()):
        return [], ("multi_hop" if "goal" in labels else "no_goal_region")
    objs = snap["edge_objects"].get(robot, {}).get("goal", set())
    if objs:
        return sorted(objs), None
    return [], "no_edge_objects"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--start", type=int, required=True)
    ap.add_argument("--end", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--budget", type=int, default=BUDGET,
                    help="simulator calls per episode (MORE collects at 300 MCTS iterations)")
    ap.add_argument("--seed-base", type=int, default=7000)
    args = ap.parse_args()

    # No checkpoint anywhere in this script. A model prior would make the collected
    # returns depend on our ranker, and MORE's whole claim is that the search supervises
    # itself from cold.
    planner, _device, _warm = _make_planner("uniform", "", 0)
    xmls = read_manifest(args.manifest, None)[args.start:args.end]
    census = {"xmls": len(xmls), "episodes": 0, "kept": 0, "solved": 0, "rows": 0, "sims": 0,
              "already_open": 0, "robot_at_goal": 0, "multi_hop": 0, "no_goal_region": 0,
              "no_edge_objects": 0, "env_error": 0}
    t0 = time.time()
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        for xi, xml in enumerate(xmls):
            try:
                env = make_env(xml)
                goal = extract_goal_with_fallback(xml, FALLBACK_GOAL)
                env.set_robot_goal(*goal)
                env.get_reachable_objects()
                gp = sample_goal_points(env)
                is_open = (lambda e, p=gp: goal_open_pts(e, p))
                if is_open(env):
                    census["already_open"] += 1
                    continue
                s0 = env.get_full_state()
                eps, reason = derive_episodes(env)
                if reason:
                    census[reason] += 1
                    continue
                for obj in eps:
                    census["episodes"] += 1
                    rows, states, solution = [], {}, {}
                    env.set_full_state(s0)
                    solved, sims, plen, _boards, _end = solve_scene_mcts(
                        planner, env, goal, xml, s0, HMAX, args.budget, "uniform", "mean5", "q",
                        random.Random(args.seed_base + ep_hash(xml, obj) % 100000),
                        restrict_obj=obj, is_open=is_open, raw=True, region_samples=gp,
                        dedupe_noop=True, prune_jam_depth=True, solution_out=solution,
                        record_out=rows, states_out=states, state_serializer=state_qpos,
                        mode="uct")
                    census["solved"] += int(solved)
                    census["kept"] += 1
                    census["rows"] += len(rows)
                    census["sims"] += sims
                    f.write(json.dumps({
                        "xml": xml, "object_id": obj, "solved": solved, "sims": sims,
                        "plan_len": plen, "budget": args.budget,
                        "rows": rows, "states": states}) + "\n")
                    f.flush()
            except Exception as e:  # noqa: BLE001  one bad scene must not kill a shard
                census["env_error"] += 1
                print(f"ERR {xml}: {type(e).__name__} {e}", flush=True)
            if xi % 20 == 0:
                print(f"{xi}/{len(xmls)} eps={census['episodes']} rows={census['rows']} "
                      f"sims={census['sims']} t={time.time()-t0:.0f}s", flush=True)
    census["wall_s"] = round(time.time() - t0, 1)
    print("CENSUS " + json.dumps(census), flush=True)


if __name__ == "__main__":
    main()
