"""MORE-inspired MCTS for region opening.

Adapted from Huang, Guo, Boularias and Yu, "Interleaving Monte Carlo Tree Search
and Self-Supervised Learning for Object Retrieval in Clutter" (ICRA 2022), read at
public revision 70402c001c30908e7a70b93f8de3c31abdd26fdb of github.com/arc-l/more.

The point of this module is a fair external comparison, so the search mechanisms
are copied rather than reinterpreted. From `mcts_network/nodes.py` we keep:

  * `best_child` scoring a child as (sum of its top-3 sampled returns + the clamped
    network prior) / visits, with no UCB term. An unexpanded child has n=1 and
    results=[0], so its score IS its prior: the net supplies the initial ordering
    and visits erode it.
  * `backpropagate` appending the sampled return and passing `result * gamma` up.
  * `rollout` running greedily on the net (`rollout_policy` picks the highest
    predicted q), returning the max discounted reward along the way.
  * `expand` dropping an action from the parent when the move does not produce a
    new state, and the transition cache keyed by path uid + move.

What we replace, and why (each substitution is a named difference, which is why
this is a MORE-INSPIRED ADAPTATION and not MORE):

  * Action library. MORE emits a fixed-distance tabletop push from an image pixel.
    We use this project's reachable (object, edge, depth) library, generated by the
    same `candidates()` call best-first uses, so both searches see one action set.
  * Reward. MORE's `PushState.push_result` shapes a grasp-quality estimate:
    0.2 * clamp(q, 0, 1), plus 1 when q clears the grasp threshold. We keep that
    exact shape and substitute the fraction of the fixed goal-region samples that
    are now reachable for q, with the canonical 20% bar as the threshold. The
    fraction is free: `count_reachable_points` already returns it alongside the
    boolean the verifier needs.
  * Termination. MORE stops on grasp success or `MCTS_MAX_LEVEL`. We stop on a
    verified opening, at `hmax`, or when a state runs out of legal actions.
  * Budget. MORE runs a fixed iteration count. We run until the episode's simulator
    budget is spent, because the comparison axis is physics attempts, not
    iterations. Every `env.step` counts, rollout steps included. Cache hits do not.

Parity with `best_first_search.solve_scene` is deliberate everywhere it does not
change MORE's algorithm: the same candidate pool, the same no-op rule (`_unmoved`),
the same jam-depth pruning, the same timing clocks, the same measurement hooks and
the same return tuple, so the evaluation harness cannot tell which planner ran.
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Tuple

from namo.planners.search_measurements import clock_start, clock_finish

from namo.planners.opening.best_first_search import (
    _record_jam_depth,
    _unmoved,
    candidates,
    make_action,
)

# constants.py of the audited revision
MCTS_DISCOUNT = 0.5
MCTS_TOP = 3                     # mcts_network/nodes.py best_child(top=3)
PRIOR_CLAMP = 1.2                # mcts_network/nodes.py: max(0, min(c.nq, 1.2))
OPEN_FRAC = 0.2                  # our GRASP_Q_PUSH_THRESHOLD analogue
MCTS_TOP_UCT = 10                # constants.py MCTS_TOP, used by the PLAIN mcts/
MCTS_UCT_RATIO = math.sqrt(2)    # constants.py MCTS_UCT_RATIO

# MORE ships TWO different searches and the paper uses both in sequence.
#
#   "uct"    = mcts/nodes.py. The COLLECTION search, System 2. No network at all:
#              mcts_main.py:480 builds its root state without a push net. Real UCT,
#              uniform-random rollouts, 300 iterations. This is what generates the
#              training data, and it is why MORE needs no checkpoint to bootstrap.
#   "guided" = mcts_network/nodes.py. The DEPLOY search, System 1 + 2. The learned
#              prior replaces the UCB term, rollouts turn greedy, and the budget
#              drops to 50 iterations. That 300 -> 50 drop is the paper's efficiency
#              claim.
#
# Both modes share this module's simulate/cache/budget/record machinery on purpose:
# the two phases must count simulator calls by the same rule or the learning-curve
# comparison measures our bookkeeping instead of the method.
MODES = ("uct", "guided")


class _Solved(Exception):
    """A verified opening. Raised from wherever it happens, including mid-rollout.

    MORE's search returns a best root action and the caller executes it. We stop at
    the first verified opening anywhere in the tree, so the exit is non-local: it can
    fire inside expand() three frames down a rollout. Threading a sentinel back
    through tree policy, expansion and rollout would obscure the MORE control flow
    this module exists to reproduce.
    """

    def __init__(self, plan, state, sims):
        self.plan = plan
        self.state = state
        self.sims = sims


class _Exhausted(Exception):
    """The episode's simulator budget is gone."""


def _push_result(frac: float, opened: bool) -> float:
    """MORE's PushState.push_result with the reachable goal-sample fraction for grasp q."""
    shaped = 0.2 * min(max(frac, 0.0), 1.0)
    return shaped + 1.0 if opened else shaped


def _scale_priors(pool, mode):
    """Put the ranker's scores into MORE's return units.

    MORE adds the network prior straight to backed-up returns and clamps it to
    [0, 1.2], which works because its net predicts a push_result in those units. A
    net trained MORE's way on our returns does too, so `raw` is correct there. Our
    existing HY5U ranker does not: its scores run well past 1.2, and clamping them
    raw would flatten the whole pool to 1.2 and throw away the ordering that is the
    entire point of the prior. `minmax` rescales each state's pool into [0, 1.2],
    which preserves the ranker's order exactly and is the honest way to hand MORE a
    prior it was not trained to produce.
    """
    if mode == "raw" or not pool:
        return [float(q) for (_o, _g, q) in pool]
    qs = [float(q) for (_o, _g, q) in pool]
    lo, hi = min(qs), max(qs)
    if hi - lo < 1e-12:
        return [PRIOR_CLAMP * 0.5] * len(qs)
    return [PRIOR_CLAMP * (q - lo) / (hi - lo) for q in qs]


class _Node:
    """nodes.py PushSearchNode. `state` is None until the move into it is simulated."""

    __slots__ = ("state", "obj", "goal", "prior", "parent", "children", "depth",
                 "uid", "n", "results", "frac", "pool", "board_id", "tries", "dead")

    def __init__(self, state, obj, goal, prior, parent, depth, uid, frac=0.0, mode="guided"):
        self.state = state
        self.obj = obj
        self.goal = goal
        self.prior = float(prior)
        self.parent = parent
        self.children: List["_Node"] = []
        self.depth = depth
        self.uid = uid
        # The two searches seed a node differently and it changes the first selection.
        # mcts_network/nodes.py:18 starts at n=1, q=[0], so an unexpanded child scores
        # exactly its prior. mcts/nodes.py:18 starts at n=0, q=[], which has no defined
        # UCT score at all, which is why the plain search expands before it selects.
        self.n = 1 if mode == "guided" else 0
        self.results = [0.0] if mode == "guided" else []
        self.frac = frac
        self.pool = None
        self.board_id = None
        self.tries: List[Tuple[int, float, bool]] = []
        # Spent or illegal, so the tree policy skips it. The node STAYS in `children`:
        # its sampled returns and visit count are the Stage-2 training evidence, and
        # detaching it would throw away the record MORE trains on.
        self.dead = False

    @property
    def live_children(self):
        return [c for c in self.children if not c.dead]

    @property
    def has_children(self):
        return any(not c.dead for c in self.children)

    def backpropagate(self, result):
        self.n += 1
        self.results.append(result)
        if self.parent is not None:
            self.parent.backpropagate(result * MCTS_DISCOUNT)

    def best_child(self, mode="guided"):
        """The selection rule, which is a different formula in each of MORE's two searches.

        guided (mcts_network/nodes.py:115):
            (sum(sorted(c.q)[-3:]) + clamp(c.nq, 0, 1.2)) / c.n        no UCB term
        uct (mcts/nodes.py:121):
            sum(sorted(c.q)[-10:]) / min(c.n, 10) + sqrt(2)*sqrt(2*ln(self.n)/c.n)

        Note the divisor differs: guided divides the summed returns by every visit,
        uct takes a mean over at most its best ten. Not interchangeable.
        """
        best, best_w = None, -math.inf
        for c in self.children:
            if c.dead:
                continue
            if mode == "uct":
                if c.n == 0:                      # never backed up, so no UCT score yet
                    continue
                w = (sum(sorted(c.results)[-MCTS_TOP_UCT:]) / min(c.n, MCTS_TOP_UCT)
                     + MCTS_UCT_RATIO * math.sqrt(2 * math.log(max(self.n, 1)) / c.n))
            else:
                w = (sum(sorted(c.results)[-MCTS_TOP:])
                     + max(0.0, min(c.prior, PRIOR_CLAMP))) / c.n
            if w > best_w:
                best, best_w = c, w
        return best

    def untried(self):
        """uct only: children whose move has not been simulated, popped from the END.

        mcts/nodes.py:49 does `self.untried_actions.pop()`, so the plain search walks
        the action list backwards. The guided search never uses this path; it
        pre-expands every child and lets best_child pick among them by prior.
        """
        return [c for c in self.children if c.state is None and not c.dead]

    def plan(self):
        """The (obj, Goal) chain from the root down to this node."""
        out, node = [], self
        while node.parent is not None:
            out.append((node.obj, node.goal))
            node = node.parent
        out.reverse()
        return out


def solve_scene_mcts(planner, env, goal, xml, s0, hmax, sim_budget, prior, agg, combine, rng,
                     restrict_obj=None, is_open=lambda e: e.is_robot_goal_reachable(),
                     raw=True, region_samples=None, dedupe_noop=True, prune_jam_depth=True,
                     timing=None, measurements=None, solution_out=None,
                     prior_scale="minmax", record_out=None, mode="guided", **_ignored):
    """MORE-inspired MCTS on the labeled object. Same contract as solve_scene.

    mode="guided" is the deploy search (mcts_network/), mode="uct" the collection
    search (mcts/). See MODES above. Collection runs with prior="uniform" so no model
    is loaded at all, which is what lets MORE bootstrap from nothing.

    Returns (solved, sims, plan_len|None, boards, end) with end in
    {solved, budget, exhausted}. `**_ignored` swallows the best-first-only knobs
    (discount, w0_mode, dive_bonus and friends) so the evaluation harness can call
    either planner with one argument list.

    record_out (list, optional): the Stage-2 training record. After the search, every
    expanded node contributes one row per child holding the child's action identity,
    its label (mcts_main.py save_mcts_data uses max(child.q)) and its visit count,
    which lifelong_trainer weights the regression by.
    """
    tm = timing
    if tm is not None:
        for key in ("t_score", "t_sim", "n_score"):
            tm.setdefault(key, 0)
    _t_wall0 = clock_start(tm)

    pts = [tuple(p[:2]) for p in (region_samples or [])]
    budget = {"sims": 0}
    cache: Dict[str, Any] = {}
    pool_cache: Dict[str, Any] = {}   # MORE move_recorder: the action list per state uid
    jam_at: Dict[Tuple, int] = {}
    boards: List[Dict[str, Any]] = []

    def open_frac(e):
        """The verifier's boolean plus the continuous fraction, from one query."""
        if not pts:
            return bool(is_open(e)), 0.0
        rc, _first = e.count_reachable_points(pts)
        return bool(is_open(e)), rc / float(len(pts))

    def score_pool(uid, state, depth):
        """The reachable pushes at one state, scored. MORE's PushState.get_actions.

        Used by expansion AND by rollouts. MORE's rollout calls get_actions too, so a
        rollout legitimately costs a scoring pass; what it must NOT do is add anything
        to the tree.

        Cached on the state's path uid, which is MORE's `move_recorder` (push.py:136).
        Without it a rollout and the later expansion of the same state each pay a model
        pass, doubling n_score and charging MORE wall-clock its own implementation
        never spends.
        """
        if uid in pool_cache:
            return pool_cache[uid]
        _t = clock_start(tm)
        pool, _V, _grid = candidates(planner, env, goal, xml, state, hmax - depth,
                                     prior, agg, rng, restrict_obj=restrict_obj, raw=raw,
                                     region_samples=region_samples, timing=tm)
        clock_finish(tm, "t_score", _t)
        if tm is not None:
            tm["n_score"] += 1
        pool_cache[uid] = pool
        return pool

    def expand_pool(node):
        """Score the state's reachable pushes and hang an unexpanded child off each."""
        pool = score_pool(node.uid, node.state, node.depth)
        node.pool = pool
        node.board_id = len(boards)
        boards.append({"board_id": node.board_id, "depth": node.depth, "n_candidates": len(pool),
                       "k_failed": 0, "w": 1.0, "w0": 1.0, "free_strikes": 0, "tries": node.tries,
                       "parent_edge": int(node.goal.edge_idx) if node.goal is not None else -1,
                       "parent_depth": int(node.goal.depth) if node.goal is not None else -1,
                       "parent_board_id": node.parent.board_id if node.parent is not None else None,
                       "pool": None, "grid": None, "geom": None, "regions": None})
        if measurements is not None:
            measurements.board(node.board_id,
                               node.parent.board_id if node.parent is not None else None,
                               node.depth, pool)
        scaled = _scale_priors(pool, prior_scale)
        for i, (obj, g, _q) in enumerate(pool):
            node.children.append(_Node(
                None, obj, g, scaled[i], node, node.depth + 1,
                f"{node.uid}.{node.depth}-{obj}_{int(g.edge_idx)}_{int(g.depth)}", mode=mode))

    def simulate(uid, state, depth, obj, g, plan, node=None):
        """One physics attempt from `state`, or a cache hit. push.py _move_result.

        `node` is the tree node when this is an expansion, and None during a rollout.
        MORE's rollout moves through PushStates and never creates a PushSearchNode, so a
        rollout step must leave the tree untouched. Letting it mark tree children as
        expanded would, under `uct`, strand them at n=0 where best_child skips them
        forever, quietly deleting candidates the search never actually ruled out.
        """
        key = f"{uid}|{obj}_{int(g.edge_idx)}_{int(g.depth)}"
        if key in cache:
            return cache[key]
        if budget["sims"] >= sim_budget:
            raise _Exhausted()
        jk = (uid, obj, int(g.edge_idx))
        jd = jam_at.get(jk)
        if prune_jam_depth and jd is not None and int(g.depth) >= jd:
            # The controller runs one continuous push, so a deeper push retraces the
            # shallower one and jams at the same tick. best_first_search makes the
            # same call, and skipping it here costs no simulator attempt.
            cache[key] = None
            return None
        env.set_full_state(state)
        obs_before = env.get_observation() if dedupe_noop else None
        action = make_action(obj, g)
        _t = clock_start(tm)
        step_res = env.step(action)
        budget["sims"] += 1
        clock_finish(tm, "t_sim", _t)
        _t = clock_start(tm)
        opened, frac = open_frac(env)
        clock_finish(tm, "t_local_verify", _t)
        info = step_res.info or {}
        if measurements is not None:
            measurements.simulated(
                board_id=node.board_id if node is not None else None,
                parent_board_id=(node.parent.board_id if node is not None and node.parent is not None
                                 else None),
                chain_depth=depth + 1, action=action, opened=opened, info=info)
        _record_jam_depth(jam_at, jk, int(g.depth), info)
        if node is not None:
            node.tries.append((len(node.tries) + 1, float(frac), opened))
            if node.board_id is not None and not opened:
                boards[node.board_id]["k_failed"] += 1
        s_after = env.get_full_state()
        if opened:
            # Bank the win BEFORE unwinding. MORE would back a push_result >= 1 up this
            # branch, and that is the single most informative label the episode produces.
            # Stopping the search first and recording nothing would hand the Stage-2
            # regression an episode whose solution is invisible.
            if node is not None:
                win = _find_child(node, obj, g)
                if win is not None:
                    win.state, win.frac = s_after, frac
                    win.backpropagate(_push_result(frac, True))
            raise _Solved(list(plan) + [(obj, g)], s_after, budget["sims"])
        if dedupe_noop and _unmoved(obs_before, env.get_observation(), obj):
            # Nothing moved, so the child would duplicate this state. MORE drops such
            # an action from the parent via remove_action; so does best-first.
            cache[key] = None
            return None
        out = (s_after, frac, opened)
        cache[key] = out
        return out

    def is_push_over(node):
        """push.py is_push_over, with the opening bar for the grasp threshold."""
        if node.depth >= hmax or node.frac > OPEN_FRAC:
            return True
        return node.pool is not None and len(node.pool) == 0

    def rollout(node):
        """nodes.py rollout: walk to terminal, return the best discounted reward seen.

        This walks STATES, not nodes, exactly as MORE does. Nothing here is added to
        the tree. The transition cache still makes a re-walked branch free, so the
        accounting is unaffected.
        """
        uid, state, depth, frac = node.uid, node.state, node.depth, node.frac
        plan = node.plan()
        pool = node.pool
        discount = 1.0
        results = [_push_result(frac, False)]
        banned = set()
        while not (depth >= hmax or frac > OPEN_FRAC):
            if pool is None:
                pool = score_pool(uid, state, depth)
            live = [(o, g, p) for (o, g, p) in zip(
                [x[0] for x in pool], [x[1] for x in pool], _scale_priors(pool, prior_scale))
                if (o, int(g.edge_idx), int(g.depth)) not in banned]
            if not live:
                break
            # rollout_policy. mcts_network/nodes.py:145 takes the highest predicted q;
            # mcts/nodes.py:134 takes `possible_moves[np.random.randint(len(...))]`,
            # uniform random, because the plain search has no net to be greedy about.
            if mode == "uct":
                obj, g, _p = live[rng.randrange(len(live))]
            else:
                obj, g, _p = max(live, key=lambda t: t[2])
            res = simulate(uid, state, depth, obj, g, plan)
            if res is None:
                banned.add((obj, int(g.edge_idx), int(g.depth)))   # push.py remove_action
                continue
            state, frac, _opened = res
            discount *= MCTS_DISCOUNT
            uid = f"{uid}.{depth}-{obj}_{int(g.edge_idx)}_{int(g.depth)}"
            plan = plan + [(obj, g)]
            depth += 1
            pool = None
            banned.clear()
            results.append(_push_result(frac, False) * discount)
        return max(results)

    def tree_policy(root):
        """nodes.py/search.py _tree_policy: descend best_child, expand the first unsimulated one."""
        cur = root
        while True:
            # Terminal FIRST, pool second. A node at hmax can never have a child
            # simulated, so scoring its pool would strand children the loop can never
            # reach and bill MORE for a model pass it cannot use.
            if is_push_over(cur):
                return cur
            if cur.pool is None:
                expand_pool(cur)
            if not cur.has_children:
                return cur
            if mode == "uct":
                # mcts/search.py:_tree_policy expands BEFORE it selects: while any action
                # is untried it pops one (from the end of the list) and simulates it,
                # and only once the node is fully expanded does UCT choose among the
                # children. The guided search cannot do this, because its children all
                # exist from the start and carry a prior instead of a visit count.
                waiting = cur.untried()
                if waiting:
                    child = waiting[-1]
                    res = simulate(cur.uid, cur.state, cur.depth, child.obj, child.goal, cur.plan(), node=cur)
                    if res is None:
                        child.dead = True
                        continue
                    child.state, child.frac = res[0], res[1]
                    return child
                child = cur.best_child(mode)
                if child is None:
                    return cur
                cur = child
                continue
            child = cur.best_child(mode)
            if child.state is None:
                res = simulate(cur.uid, cur.state, cur.depth, child.obj, child.goal, cur.plan(), node=cur)
                if res is None:
                    child.dead = True
                    continue
                child.state, child.frac = res[0], res[1]
                return child
            cur = child

    def _find_child(node, obj, g):
        for c in node.children:
            if c.obj == obj and c.goal.edge_idx == g.edge_idx and c.goal.depth == g.depth:
                return c
        return None

    def _is_dead(node):
        """Nothing beneath this node can ever produce another physics attempt."""
        if node.has_children:
            return False
        return node.depth >= hmax or node.pool is not None

    def _prune_exhausted(node):
        """Detach a node the search can never get anything more out of, and its parents.

        MORE runs a fixed number of iterations, so re-descending to a spent leaf costs
        it nothing it measures. Our loop runs until the simulator budget is gone, and a
        selection that ends at a dead leaf spends no sim while still burning wall-clock,
        which is the headline metric here. Measured before this pruning: 400 iterations
        bought 42 attempts. Detaching cannot reorder or drop any physics attempt, since
        a dead node has none left to give.
        """
        cur = node
        while cur.parent is not None and _is_dead(cur):
            cur.dead = True
            cur = cur.parent

    def _remove_action(node, obj, g):
        """push.py remove_action: the move is gone from this state for good."""
        c = _find_child(node, obj, g)
        if c is not None and c.state is None and not c.dead:
            c.dead = True

    root = _Node(s0, None, None, 0.0, None, 0, "r", mode=mode)
    solved, sims, plen, end = False, 0, None, "exhausted"
    try:
        expand_pool(root)
        # Termination is _prune_exhausted marking spent subtrees dead until the root
        # has no live child left. An earlier version also required a count of
        # not-yet-simulated children to be positive, which silently broke `uct`: the
        # lazy expansion drains that count across the root's own children before it
        # ever descends, so the search stopped after one level.
        while root.has_children and budget["sims"] < sim_budget:
            node = tree_policy(root)
            reward = rollout(node)
            node.backpropagate(reward)
            _prune_exhausted(node)
        end = "budget" if budget["sims"] >= sim_budget else "exhausted"
        sims = budget["sims"]
    except _Solved as hit:
        solved, sims, end = True, hit.sims, "solved"
        plen = len(hit.plan)
        if solution_out is not None:
            solution_out["plan"] = list(hit.plan)
            solution_out["state"] = hit.state
    except _Exhausted:
        sims, end = budget["sims"], "budget"
    clock_finish(tm, "t_wall", _t_wall0)

    if record_out is not None:
        _collect_records(root, record_out)
    return solved, sims, plen, boards, end


def _collect_records(root, out):
    """mcts_main.py save_mcts_data: walk the tree, one row per child of an expanded node.

    label = max(child.q), weight = the child's visit count. lifelong_trainer multiplies
    the SmoothL1 term by that weight, so an action the search barely looked at barely
    moves the net. Cells with no sampled evidence get no row, and therefore no weight,
    which is how MORE keeps unexplored actions out of the regression instead of
    stamping them as failures.
    """
    queue = [root]
    while queue:
        node = queue.pop(0)
        # `children`, not `live_children`: a spent action is still evidence, and its
        # visit count is exactly what tells the regression how much to trust its label.
        if node.children and node.state is not None:
            for c in node.children:
                # `evidence` is ours, not MORE's. MORE writes a row for every child of an
                # expanded node, so an action the search never tried lands in the dataset
                # with label 0 and weight 1, which reads as "this push fails" when all it
                # means is "nobody looked". One easy episode here produced 144 such rows
                # and zero sampled ones. Keeping MORE's rows preserves fidelity; the tag
                # lets the trainer drop them and lets the card report both ways.
                out.append({"uid": node.uid, "depth": node.depth, "obj": c.obj,
                            "edge": int(c.goal.edge_idx), "push_depth": int(c.goal.depth),
                            "label": float(max(c.results)), "num_visits": int(c.n),
                            "expanded": c.state is not None,
                            "evidence": "sampled" if (c.state is not None or c.dead) else "unsampled"})
            queue.extend(c for c in node.children if c.state is not None)
