#!/bin/bash
# v5 end-to-end, autonomous: wait for maps -> reduce (both arms in parallel) -> gate -> train -> eval.
#
# v5 = the 0.5-ladder file (arjuna0v2_train.h5: floor applied, setup 0.5) + guesses regenerated by
# a 0.5-TRAINED model, at gamma 0.5. Each arm bootstraps from its own kind of model:
#     AJ5    <- V-hat from AJ2   (0.5 ladder, aux ON)    trained aux ON
#     AJ5NR  <- V-hat from AJ2NR (0.5 ladder, aux OFF)   trained aux OFF
# Controls are exact: AJ2 (26.8) and AJ2NR (20.0) are the same files minus the guesses, so the
# only difference is the guesses themselves.
#
# gamma 0.5 is NOT cosmetic [USER caught this]: a guess is gamma*V-hat and a known setup is
# gamma*1, so at gamma 0.9 into a 0.5 file, 22.1% of guesses outrank a verified setup.
set -u
R0=/common/users/dm1487/scratch_namo/aquaman/round0
MAIN=/common/home/dm1487/robotics_research/ktamp/namo
# Repo is resolved, never hardcoded: these were written inside a git worktree and used to
# pin it alive by absolute path (ORCHESTRATION.md says prune worktrees after merge-back;
# a hardcoded WT= made that impossible). scripts/rl_loop/phase0_gate.slurm still points at
# an agent worktree that no longer exists -- same bug, already fired.
WT=${NAMO_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}
PY=/common/users/dm1487/envs/mjxrl/bin/python
SUB=ilab2.cs.rutgers.edu
SRC=$R0/arjuna0v2_train.h5

for i in $(seq 1 180); do
  a=$(ls $R0/v5_aj2/*.npy 2>/dev/null | wc -l); b=$(ls $R0/v5_aj2nr/*.npy 2>/dev/null | wc -l)
  [ "$a" -ge 32 ] && [ "$b" -ge 32 ] && break
  echo "[$(date +%H:%M)] maps aj2=$a/32 aj2nr=$b/32"; sleep 60
done
[ "$a" -ge 32 ] && [ "$b" -ge 32 ] || { echo "ABORT: maps incomplete a=$a b=$b"; exit 1; }
echo "MAPS DONE $(date)"

# both reduces at once -- they read disjoint edit dirs and write disjoint outputs
cd "$WT"
"$PY" scripts/rl_loop/aquaman_rebuild_v2.py reduce --arm Bfix --gamma 0.5 --src "$SRC" \
   --work $R0/v5_aj2   --out $R0/arjuna0v5_train.h5   > $R0/reduce_v5_aj2.log 2>&1 &
P1=$!
"$PY" scripts/rl_loop/aquaman_rebuild_v2.py reduce --arm Bfix --gamma 0.5 --src "$SRC" \
   --work $R0/v5_aj2nr --out $R0/arjuna0v5nr_train.h5 > $R0/reduce_v5_aj2nr.log 2>&1 &
P2=$!
wait $P1 $P2
echo "REDUCES DONE $(date)"; tail -2 $R0/reduce_v5_aj2.log; tail -2 $R0/reduce_v5_aj2nr.log

# GATE: no GPU is touched unless both files look right.
"$PY" - <<'EOF' || { echo "GATE FAILED -- not training"; exit 1; }
import h5py, numpy as np, sys
R0="/common/users/dm1487/scratch_namo/aquaman/round0"
ok=True
for tag,p in (("AJ5",f"{R0}/arjuna0v5_train.h5"),("AJ5NR",f"{R0}/arjuna0v5nr_train.h5")):
    f=h5py.File(p,"r"); n=int(f.attrs["n_samples"]); step=max(1,n//2500)
    ng=[]; gv=[]
    for i in range(0,n,step):
        r=f["r_mask"][i]>0.5; v=f["value_mask"][i]>0.5
        g=f["guess_mask"][i]>0.5 if "guess_mask" in f else np.zeros_like(r)
        ng.append(f["value_target"][i][v&r&~g]); gv.append(f["value_target"][i][g&r])
    a=np.concatenate(ng); ga=np.concatenate(gv); f.close()
    u=np.unique(np.round(a,3)); over=(ga>0.5).mean() if ga.size else 0
    print(f"{tag}: non-guess={u[:5]} guesses n={ga.size} max={ga.max() if ga.size else 0:.3f} "
          f"above_setup={100*over:.1f}%")
    # the whole point: gamma 0.5 must keep every guess at or below the known setup label
    if ga.size==0 or over>0.001 or len(u)>3: ok=False
sys.exit(0 if ok else 1)
EOF
echo "GATE PASSED $(date)"

for s in 1 2 3; do
  ssh $SUB "cd $WT && NAMO_REPO=$WT SAGE_REPO=${SAGE_REPO:-/common/home/dm1487/robotics_research/ktamp/sage_learning} H5=$R0/arjuna0v5_train.h5 OUT=$R0/models/AJ5_s$s SEED=$s EPOCHS=12 RANK_LAMBDA=0.1 LOWER_RANK_LAMBDA=0.1 NAMO_RANK_EXCLUDE_GUESS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True sbatch --time=04:00:00 --mem=24G --job-name=AJ5_s$s --exclude=ilab1,ilab4,rlab7 scripts/slurm/train.slurm" 2>&1 | tail -1
  ssh $SUB "cd $WT && NAMO_REPO=$WT SAGE_REPO=${SAGE_REPO:-/common/home/dm1487/robotics_research/ktamp/sage_learning} H5=$R0/arjuna0v5nr_train.h5 OUT=$R0/models/AJ5NR_s$s SEED=$s EPOCHS=12 RANK_LAMBDA=0 LOWER_RANK_LAMBDA=0 NAMO_RANK_EXCLUDE_GUESS=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True sbatch --time=04:00:00 --mem=24G --job-name=AJ5NR_s$s --exclude=ilab1,ilab4,rlab7 scripts/slurm/train.slurm" 2>&1 | tail -1
done
echo "V5 TRAINS SUBMITTED $(date)"
