# High-Level Planning Demo Test Configuration
# Optimized settings to avoid BFS queue overflow

planning:
  high_level_resolution: 0.05      # 5cm grid for reachability analysis (reduced from 2cm)
  skill_level_resolution: 0.02     # 2cm grid for detailed skill planning (increased from 0.5cm)
  max_iterations: 10
  verbose: true
  robot_size: [0.15, 0.15]
  robot_goal: [0.54, -0.84]
  max_bfs_queue: 100000
  max_grid_width: 2000
  max_grid_height: 2000
  max_changes: 10000
  position_threshold: 0.0001
  rotation_threshold: 0.001
  small_rotation_limit: 0.05

strategy:
  random:
    min_goal_distance: 0.3
    max_goal_distance: 1.0
    max_goal_attempts: 100
    max_object_retries: 100
  ml:
    zmq_endpoint: "tcp://localhost:5555"
    timeout_ms: 1000
    fallback_to_random: true

skill:
  max_push_steps: 10
  max_mpc_iterations: 2
  control_steps_per_push: 250
  force_scaling: 1.0
  robot_size: [0.15, 0.15, 0.15]
  execution_timeout: 30.0
  goal_tolerance: 0.1
  stuck_threshold: 0.01
  max_stuck_iterations: 3
  object_clearance: 0.1
  num_edge_points: 12

environment:
  max_static_objects: 20
  max_movable_objects: 10
  max_actions: 100
  max_motion_primitives: 1000
  max_planning_nodes: 10000
  log_buffer_size: 100000
  enable_logging: false
  log_directory: "logs/"

system:
  enable_visualization: false       # Disable visualization to avoid GLFW issues
  enable_profiling: false
  num_threads: 1
  motion_primitives_file: "data/motion_primitives.dat"
  default_scene_file: "/common/home/dm1487/robotics_research/ktamp/ml4kp_ktamp/resources/models/custom_walled_envs/aug9/easy/set2/benchmark_1/env_config_232a.xml"
  collect_training_data: false
  training_data_directory: "training_data/"

simulation:
  timestep: 0.001
  solver_iterations: 10
  gravity: [0, 0, -9.81]
  contact_softness: 0.001
  contact_damping: 0.0001
  camera_distance: 5.0
  camera_azimuth: 90.0
  camera_elevation: -45.0

wavefront_planner:
  resolution: 0.01
  robot_inflation: 0.05
  max_distance: 1000
  diagonal_cost: 1.414
  enable_incremental_updates: true
  cache_static_obstacles: true
  save_debug_grids: false
  debug_grid_directory: "debug_grids/"

motion_primitives:
  max_push_steps: 10